### PR TITLE
Consider a Formula-per-version approach. Get rid of `timescale_move.sh`

### PR DESCRIPTION
**Pull request by rtwalker**
* Make timescale_move.sh unnecessary
* Rewrite test to try create extension
* Other minor formula improvements

### CODE REVIEW

**Review by svenklemm — COMMENTED** [review]
How will this deal with multiple versions? Will it still be possible to have TimescaleDB 2.7.0 and 2.8.0 installed? Will it remove previous version files on version update?

**Comment by rtwalker** [comment]
> How will this deal with multiple versions? [...] Will it remove previous version files on version update?

This is mostly handled at the Homebrew level. 

Currently when a user runs `brew install timescaledb`, the extension files will be installed to (on M1 Mac) `/opt/homebrew/Cellar/timescaledb/2.8.0`.  

If there's new release and the user later runs `brew upgrade timescaledb`, then those files are put in e.g. `/opt/homebrew/Cellar/timescaledb/2.8.1`.

Both of those will exist for some time--either until the user runs `brew cleanup` or (at least as a default behavior) Homebrew itself runs cleanup globally periodically. However, (I'm pretty sure) only the newest version will be symlinked into the directories pointed to by `pg_config --libdir --sharedir`.

Users can configure the Homebrew cleanup settings such that it's certainly possible to keep many versions around.

However, there's not really a good way to start from `brew install timescaledb` and get anything other than the latest version.

> Will it still be possible to have TimescaleDB 2.7.0 and 2.8.0 installed?  

This PR doesn't make it any less possible, but the answer mostly depends on what already exists in `/opt/homebrew/Cellar/timescaledb` on the user's machine and on how `brew` manages upgrades.

To make it ~more possible~ pretty easy, we could additionally offer versioned formulae e.g. `timescaledb@2.7` and `timescaledb@2.8` (they'd just have to have their own files). These would only upgrade for patch releases and not across minor versions. Further it would be possible to separately have a `timescaledb` formula as an alias for the latest version. 

Even further, we currently only work with `postgresql@14` but we could consider having both `timescaledb-pg13@2.8` and `timescaledb-pg14@2.8` offerings.

**Review by jonatas — APPROVED** [review]
I tested locally, it worked as expected!

The only extra sign I have here was that I needed to relink timescaledb:

```
brew unlink timescaledb && brew link timescaledb
```

Multi-versioned formulas between PG and Timescale is a kind of dream that will probably be a nightmare to maintain 😄 

It can give people some flexibility in local development but not sure how often we need to encourage people to use the old versions.

I'm actually using docker to run the old versions when I need them.

**Comment by rtwalker** [comment]
> Multi-versioned formulas between PG and Timescale is a kind of dream that will probably be a nightmare to maintain 😄
> 
> It can give people some flexibility in local development but not sure how often we need to encourage people to use the old versions.
> 
> I'm actually using docker to run the old versions when I need them.

Yeah I'm not sure that we *should* do any of those things... I'm guessing that if people are choosing to use `brew` for this, they probably expect some amount of the default behavior and won't be clinging too tightly to older versions.

**Comment by svenklemm** [comment]
If the shared libraries in pg_config --libdir --sharedir are now managed by homebrew and only 1 version will be symlinked then your change is a regression. Each database has its own timescaledb version and when previous binaries do not persist after installing more recent version then this will break installation. That was the reason for the move script to decouple the binaries from brew management and persist them.

**Comment by rtwalker** [comment]
> That was the reason for the move script to decouple the binaries from brew management and persist them.

Hmm I guess I hadn't considered the case of wanting to install via `brew` but not have it manage upgrades in a typical fashion. I'll think some more about what else could be done here. Thanks for the feedback!

**Comment by rtwalker** [comment]
> we could additionally offer versioned formulae e.g. `timescaledb@2.7` and `timescaledb@2.8` (they'd just have to have their own files). These would only upgrade for patch releases and not across minor versions. Further it would be possible to separately have a `timescaledb` formula as an alias for the latest version.

@svenklemm do you think would this approach work?

Offering versioned formulae would give users the ability to install any version of the extension available without the risk of losing older versions with an upgrade. Further all installed versions would be appropriately symlinked into the `pg_config --libdir --sharedir` 

I'm curious whether it's important that e.g. 2.8.0 binaries persist after an upgrade to 2.8.1. We could of course offer `timescaledb@2.8.0` and `timescaledb@2.8.1` at which point `brew upgrade ...` should leave things untouched. This would just mean a new file for every release. 

I'd really like to make it possible to `brew install timescaledb` without having to run the `timescale_move.sh` and am hopeful that we can figure out a way to make the install process a little more conventional (w.r.t. Homebrew) while still being considerate of the various needs at hand.

**Comment by svenklemm** [comment]
> > we could additionally offer versioned formulae e.g. `timescaledb@2.7` and `timescaledb@2.8` (they'd just have to have their own files). These would only upgrade for patch releases and not across minor versions. Further it would be possible to separately have a `timescaledb` formula as an alias for the latest version.
> 
> @svenklemm do you think would this approach work?
> 
> Offering versioned formulae would give users the ability to install any version of the extension available without the risk of losing older versions with an upgrade. Further all installed versions would be appropriately symlinked into the `pg_config --libdir --sharedir`

I don't have strong oppinions how the implementation looks like but it should be priority that we dont break installations.
Here is the scenario why we need old binaries to stick around:
User installs timescaledb 2.0 and creates database DB2.0
Now user installs timescaledb 2.1 and creates database DB2.1
If the previous step removed the 2.0 binaries DB2.0 will stop working. Only after upgrading DB2.0 to 2.1 will the timescaledb 2.0 binaries no longer be needed. Every postgres database is linked to specific timescaledb version and can be upgraded independantly so you need to have the binaries for all the versions in use.

> I'm curious whether it's important that e.g. 2.8.0 binaries persist after an upgrade to 2.8.1. We could of course offer `timescaledb@2.8.0` and `timescaledb@2.8.1` at which point `brew upgrade ...` should leave things untouched. This would just mean a new file for every release.

Every binary that was present should stay cause the exact binary is needed if a database with that version is still present.

> I'd really like to make it possible to `brew install timescaledb` without having to run the `timescale_move.sh` and am hopeful that we can figure out a way to make the install process a little more conventional (w.r.t. Homebrew) while still being considerate of the various needs at hand.

I'm all for improving the workflow. I'm not a mac user so I can't help much here, but I wanna make sure we don't break existing installations on update.

**Comment by rtwalker** [comment]
> > We could of course offer timescaledb@2.8.0 and timescaledb@2.8.1 at which point brew upgrade ... should leave things untouched. This would just mean a new file for every release.
>
> Every binary that was present should stay cause the exact binary is needed if a database with that version is still present.
> 
> > I'd really like to make it possible to `brew install timescaledb` without having to run the `timescale_move.sh` and am hopeful that we can figure out a way to make the install process a little more conventional (w.r.t. Homebrew) while still being considerate of the various needs at hand.
> 
> I'm all for improving the workflow. I'm not a mac user so I can't help much here, but I wanna make sure we don't break existing installations on update.

That sounds like a super reasonable constraint. I'll convert this PR to a mockup of what it would look like to be able to specify any version for installation.

**Comment by rtwalker** [comment]
> Here is the scenario why we need old binaries to stick around:
> User installs timescaledb 2.0 and creates database DB2.0
> Now user installs timescaledb 2.1 and creates database DB2.1
> If the previous step removed the 2.0 binaries DB2.0 will stop working. Only after upgrading DB2.0 to 2.1 will the timescaledb 2.0 binaries no longer be needed. Every postgres database is linked to specific timescaledb version and can be upgraded independantly so you need to have the binaries for all the versions in use.

What happens in this scenario when the user acquired timescaledb 2.0 via e.g. 
`apt install timescaledb-2-postgresql-14`? Would be good to learn from how we've solved this problem elsewhere.

**Comment by rtwalker** [comment]
> I'll convert this PR to a mockup of what it would look like to be able to specify any version for installation.

In the meantime, I've opened #27 from the two commits that were here but aren't really relevant to the discussion above.

**Comment by rtwalker** [comment]
I still think this would be an improvement, but that will have to be for someone else to decide.

**Pull request closed without merging**
